### ISSUE TITLE
kraken-pcap 1.5 is unavailable

### ISSUE THREAD

**Issue by missdiog** [OpenSOC/opensoc-streaming#3]
http://download.krakenapps.org  is down,I can't open the website for download the kraken-pcap 1.5 jar.would you show me another adreess

**Comment by danielyangmeta** [comment]
http://download.krakenapps.org is down and the /etc/hosts hack is down too.can u help me how to solve the problem?

**Comment by sainib** [comment]
Just reporting that remote repo domains are still down. I tried compiling the source code at https://github.com/nchovy/kraken but it has cyclic dependencies. Anything I can help with to resolve this issue? Please let me know.. 

For those experiencing the similar issue - I have been able to compile Open SOC Streaming project using the pcap code here - https://github.com/dangle0118/lab.git .. which I think is a much older version of the kraken apps pcap code. I had to get rid of smtp decoder package because that needed mime package from kraken apps .. not even close to what I wanted but at this point I just want to get it all up and running ..

**Comment by missdiog** [comment]
yeah, The host 14.63.217.52 is  down , I have upload the jars into onedriver . 
a ./kraken
a ./kraken-api
a ./kraken-pcap
a ./krakenapps.tar: Can't add archive to itself
a ./kraken-pcap/1.5.0
a ./kraken-pcap/1.5.0/_maven.repositories
a ./kraken-pcap/1.5.0/kraken-pcap-1.5.0.jar
a ./kraken-pcap/1.5.0/kraken-pcap-1.5.0.jar.sha1
a ./kraken-pcap/1.5.0/kraken-pcap-1.5.0.pom
a ./kraken-pcap/1.5.0/kraken-pcap-1.5.0.pom.lastUpdated
a ./kraken-pcap/1.5.0/kraken-pcap-1.5.0.pom.sha1
a ./kraken-api/1.6.0
a ./kraken-api/1.6.0/_maven.repositories
a ./kraken-api/1.6.0/kraken-api-1.6.0.jar
a ./kraken-api/1.6.0/kraken-api-1.6.0.jar.sha1
a ./kraken-api/1.6.0/kraken-api-1.6.0.pom
a ./kraken-api/1.6.0/kraken-api-1.6.0.pom.sha1
a ./kraken/1.0.0
a ./kraken/1.0.0/_maven.repositories
a ./kraken/1.0.0/kraken-1.0.0.pom
a ./kraken/1.0.0/kraken-1.0.0.pom.lastUpdated
a ./kraken/1.0.0/kraken-1.0.0.pom.sha1

link: http://1drv.ms/15yOjI9

Have good time for opensoc

**Comment by sainib** [comment]
Thanks missdiog!

**Comment by gouye** [comment]
http://1drv.ms/15yOjI9   cannot download now .who can help me

**Comment by gouye** [comment]
missdiog,help me

**Comment by tpiscitell** [comment]
We stood up our own maven repo for Kraken. Pull the latest changes from the master branch and rebuild.
